name: wallet_ui
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  modal_bottom_sheet: ^2.0.0


  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.1.0
  shared_preferences: ^2.0.13
  local_auth: ^1.1.11
  flutter_screen_lock: ^5.0.6+1
  flutter_bloc: ^8.0.0
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  build_runner: ^2.0.6
  get_it: ^7.2.0
  dio: ^4.0.4
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.13
  flutter_styled_toast: ^2.0.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  image_picker: ^0.8.5+3
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/home_screen_finances/
    - assets/images/payment_screen_images/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
